FPS=50
#ScreenType="Splash"
ScreenType="Init"
#ScreenType="Diff"
#ScreenType="Long"
#ScreenType="Ready"
#ScreenType="Score"
#ScreenType="Over"
#ScreenType="Exit"
Debugging=false
OptionType="A"
DifficultyType="Easy"
SplashDelay=3000
TitleDelay=800
OptionDelay=1000
DotsDelay=1750
BlankSplash=true
FlashTitle=true
MusicEnable=true
SoundEnable=true
#CheatMode=true
CheatMode=false
RandomQuestions=false
RandomAnswers=false
Fullscreen=false