FPS=50
#ScreenType="Splash"
#ScreenType="Init"
#ScreenType="Title"
ScreenType="Diff"
#ScreenType="Long"
#ScreenType="Ready"
#ScreenType="Exit"
Debugging=false
OptionType="D"
DifficultyType="Argh"
SplashDelay=3000
TitleDelay=800
ReadyDelay=7500
DotsDelay=1000
OverDelay=3000
PlayDelay=15000
BlankSplash=true
FlashTitle=true
MusicEnable=true
SoundEnable=true
CheatMode=false
RandomQuestions=true
RandomAnswers=true
Fullscreen=false