apiVersion: v1
kind: Service
metadata:
  name: testwebapi-service
  namespace: env-vars
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8080
  selector:
    app: testwebapi