apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: your-docker-image:latest  # Use your built Docker image here
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
