---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-ml-service
  namespace: test-ns
  labels:
    app: azure-ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-ml-service
  template:
    metadata:
      labels:
        app: azure-ml-service
    spec:
      containers:
      - name: azure-ml-service
        image: azure-ml-local:latest
        imagePullPolicy: IfNotPresent  # Use for local images
        ports:
        - containerPort: 5001
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: AZUREML_MODEL_DIR
          value: "/app/model"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-ml-service
  namespace: test-ns
spec:
  type: NodePort  # Makes the service accessible outside cluster
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: azure-ml-service